export const SHOPING_CART_SELECTORS = {
    
    SHOPPING_CART_MODAL: 'aside.fixed.h-full.w-full.md\\:w-1\\/3.right-0.z-40.bg-white',
    CART_GRID_CONTAINER: 'div.cart-grid',
    CLOSE_BUTTON: 'button.hover\\:scale-105.duration-200',
    FIRST_PRODUCT_IMAGE: '.cart-items :nth-child(1).cart-grid.items-center :nth-child(1)',
    FIRST_PRODUCT_NAME: '.cart-items :nth-child(1).cart-grid.items-center :nth-child(2)',
    FIRST_PRODUCT_QUANTITY: '.cart-items :nth-child(1).cart-grid.items-center :nth-child(3)',
    FIRST_PRODUCT_PRICE: '.cart-items :nth-child(1).cart-grid.items-center :nth-child(4)',
    FIRST_PRODUCT_DELETE:  '.cart-items :nth-child(1).cart-grid.items-center :nth-child(5)',
    SECOND_PRODUCT_IMAGE: '.cart-items :nth-child(2).cart-grid.items-center :nth-child(1)',
    SECOND_PRODUCT_NAME: '.cart-items :nth-child(2).cart-grid.items-center :nth-child(2)',
    SECOND_PRODUCT_QUANTITY: '.cart-items :nth-child(2).cart-grid.items-center :nth-child(3)',
    SECOND_PRODUCT_PRICE: '.cart-items :nth-child(2).cart-grid.items-center :nth-child(4)',
    SECOND_PRODUCT_DELETE:  '.cart-items :nth-child(2).cart-grid.items-center :nth-child(5)',
    HEADER_IMAGE:'.cart-grid p:nth-child(1)',
    HEADER_NAME:'.cart-grid p:nth-child(2)',
    HEADER_QUANTITY:'.cart-grid p:nth-child(3)',
    HEADER_PRICE:'.cart-grid p:nth-child(4)',
    HEADER_DELETE:'.cart-grid p:nth-child(5)',
    TOTAL: 'p.text-black.text-center',
    NO_ELEMENTS_MESSAGE: 'p.text-center.text-gray-600',
    GO_TO_CHECKOUT_BUTTON: 'button.bg-primaryColor.text-white.p-3.rounded-lg.w-full.primary-cta-hover',
    EMPTY_CART_BUTTON: 'button[data-at="empty-cart"]',   
}